### PR TITLE
General code cleanup - Efficiency improvements - Potential IOException fixes

### PR DESCRIPTION
**Pull request by 2008Choco**
pom.xml:
- Removed Apache Commons IO and GSON from pom.xml dependencies. Spigot shades both of these libraries

XenSync:
+ Added private fields to properly encapsulate respective fields
* Renamed a couple fields to give a better idea as to what they do
+ Added instance fields for "Gson", "Type" and "Random" which only need to be declared once
* Reorganized the onEnable() to be in a more proper and acceptable order (i.e. setup data storage first, configuration loading second, etc.)
* Un-nested a whole bunch of if statements that had no need to be nested. Easy readability
- Removed unnecessary boolean comparisons in conditional statements (== true and == false)
+ Added Java 8 support using Stream API / Lambdas where required
* Replaced "#setupConversionFile()" and "#setupExceptionFile()" methods with a single "initializeFile(String, Function)" file to allow for more flexibility in file creation / parsing
- Removed instantiation of the com.mysql.jdbc.Driver class, as it only needs to be called upon to initialize its fields / methods, etc.
* Replaced unnecessary if statements with ternary operands
- Removed "warn()" and "info()" methods. They were creating runnables for every single method... which is extremely overkill. Logger#warning() and Logger#info() should suffice
- Removed unnecessary if/else statement for "useUsername" in the "/register" command. Used ternary for the "site" variable based on the boolean instead. (Shaves off ~30 lines)
* Fixed common JsonSyntaxExceptions, and also threw a try/catch around it to make it more pretty to the client-user
* Wrapped many Reader objects in BufferedReader objects, because InputStreamReaders can be resource intensive if not wrapped
+ Properly implemented the "xenforo-registration.enable" configuration option. This was not being used at all...

To be honest, there were so many issues with the plugin; not only code-wise, but also syntax and convention-wise. I've taken the liberty to fix as much as I possibly could. Of course, it's not perfect, but I fixed everything I thought needed it :) I shaved off at least 90 lines of useless code

I hope you can find the time to approve this :) Also! I really want to note something that I noticed while messing around with this; Connections to servers (or websites) protected with CloudFlare will fail with an HTTP response code of 400 unless CloudFlare is configured to allow this program to bypass it. Although that's not your problem, I just thought I would inform you.

### CODE REVIEW

**Comment by philip-ulrich** [comment]
Much appreciated! If I were to say that I'm a java programmer or even that I like Java, I would be lying. I also inherited a bit of this code from the previous maintainer. ;) Let me review this, get a build server back up, test, and if it's good, I'll merge it and do a release. 

Once again, thanks for taking the time to work on and and improve it! I haven't had much of a chance to work on it recently and cleaning it up was on my to-do list.

**Comment by 2008Choco** [comment]
No problem! I actually enjoyed cleaning this up a bit! A server I've been developing is going to be using this and we noticed some issues regarding CloudFlare, but while I was at attempting to fix it, I thought I would pull request and clean up a bit of the code using some new Java 8 features n' general improvements all around based on Java code conventions.

Hope to see a release on this soon! If it has any issues, let me know and I'll see if I can commit a fix for it

**Comment by philip-ulrich** [comment]
Heh. That's kinda how I ended up taking this over from the other author. I wanted the registration function implemented for my mc server, but I've since dropped it and my motivation to work on this over other projects is low. I'm working on setting up jenkins now. Prob get the release out before the weekend unless I see stuff I need to fix of yours. :P I might have you test it post build if you haven't yet since my dev server is gone right now as well.

**Comment by 2008Choco** [comment]
I mean, as far as I've tested, it seems to work. Though I can't 100% guarantee that. -\_(''/)_/-

**Comment by philip-ulrich** [comment]
That'll do. I'll add a caveat that people should be sure to test it before deploying to production... which they always should do, but... :1st_place_medal:

**Comment by philip-ulrich** [comment]
merging pre-maturely because I'm having jenkins issues and using travis.. travis doesn't like this PR though because it existed before I added this to travis.

**Comment by philip-ulrich** [comment]
@2008Choco Give this a shot if you don't mind and let me know if it passes base functionality checks: https://github.com/philip-ulrich/XenSync/releases/download/1.0.3-release/XenSync-1.0.3-SNAPSHOT.jar

**Pull request merged**
